#!/bin/bash

echo "$CODE_REPOSITORY_SECRETS" \
| jq -r 'to_entries[] | [.key, (.value|tostring)] | @tsv' \
| while IFS=$'\t' read -r key value; do
  echo "Creating secret: $key"
  if printf '%s' "$value" | gh secret set "$key" --repo "$GITHUB_ACCOUNT/$REPOSITORY_NAME"; then
    echo "Secret $key created successfully"
  else
    echo "Error creating $key secret"
  fi
done
